# Generated by Django 4.2.3 on 2024-11-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_drive_app', '0002_folder_userfile_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent',
            new_name='parent_folder',
        ),
    ]
